<?php

namespace Chaire\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventFriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventFriseRepository extends EntityRepository
{
}
