<?php

namespace Proxies\__CG__\Chaire\TeamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Team extends \Chaire\TeamBundle\Entity\Team implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'id', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'name', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'firstname', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'title', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'bio', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'twitter', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'linkedin', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'category', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'filephoto', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'photolink');
        }

        return array('__isInitialized__', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'id', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'name', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'firstname', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'title', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'bio', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'twitter', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'linkedin', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'category', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'filephoto', '' . "\0" . 'Chaire\\TeamBundle\\Entity\\Team' . "\0" . 'photolink');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Team $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLinkedin($linkedin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedin', array($linkedin));

        return parent::setLinkedin($linkedin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedin', array());

        return parent::getLinkedin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBio($bio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBio', array($bio));

        return parent::setBio($bio);
    }

    /**
     * {@inheritDoc}
     */
    public function getBio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBio', array());

        return parent::getBio();
    }

    /**
     * {@inheritDoc}
     */
    public function getFilephoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilephoto', array());

        return parent::getFilephoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilephoto(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilephoto', array($file));

        return parent::setFilephoto($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotolink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotolink', array());

        return parent::getPhotolink();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotolink($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotolink', array($photo));

        return parent::setPhotolink($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

}
