<?php

namespace Proxies\__CG__\Chaire\EventBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \Chaire\EventBundle\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'id', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventName', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventDescription', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventDate', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'Logo', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'Imageentete', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'page', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventAddress');
        }

        return array('__isInitialized__', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'id', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventName', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventDescription', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventDate', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'Logo', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'Imageentete', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'page', '' . "\0" . 'Chaire\\EventBundle\\Entity\\Event' . "\0" . 'eventAddress');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Event $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPage($page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPage', array($page));

        return parent::setPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPage', array());

        return parent::getPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageentete($Imageentete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageentete', array($Imageentete));

        return parent::setImageentete($Imageentete);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageentete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageentete', array());

        return parent::getImageentete();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($Logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', array($Logo));

        return parent::setLogo($Logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventAddress(\Chaire\AdminBundle\Entity\Address $address = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventAddress', array($address));

        return parent::setEventAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventAddress', array());

        return parent::getEventAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventName($eventName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventName', array($eventName));

        return parent::setEventName($eventName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventName', array());

        return parent::getEventName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventDescription($eventDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventDescription', array($eventDescription));

        return parent::setEventDescription($eventDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventDescription', array());

        return parent::getEventDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventDate($eventDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventDate', array($eventDate));

        return parent::setEventDate($eventDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventDate', array());

        return parent::getEventDate();
    }

}
