<?php

namespace Proxies\__CG__\Chaire\AccueilBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Accompagnement extends \Chaire\AccueilBundle\Entity\Accompagnement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'id', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'nameLg', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'nameEn', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'baselineLg', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'baselineEn', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'Logo', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'Imageentete', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'page', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'pageEn');
        }

        return array('__isInitialized__', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'id', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'nameLg', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'nameEn', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'baselineLg', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'baselineEn', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'Logo', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'Imageentete', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'page', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Accompagnement' . "\0" . 'pageEn');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Accompagnement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPageEn($pageEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageEn', array($pageEn));

        return parent::setPageEn($pageEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageEn', array());

        return parent::getPageEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageentete($Imageentete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageentete', array($Imageentete));

        return parent::setImageentete($Imageentete);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageentete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageentete', array());

        return parent::getImageentete();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($Logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', array($Logo));

        return parent::setLogo($Logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPage($page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPage', array($page));

        return parent::setPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPage', array());

        return parent::getPage();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameLg($nameLg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameLg', array($nameLg));

        return parent::setNameLg($nameLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameLg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameLg', array());

        return parent::getNameLg();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameEn($nameEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameEn', array($nameEn));

        return parent::setNameEn($nameEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameEn', array());

        return parent::getNameEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaselineLg($baselineLg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaselineLg', array($baselineLg));

        return parent::setBaselineLg($baselineLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaselineLg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaselineLg', array());

        return parent::getBaselineLg();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaselineEn($baselineEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaselineEn', array($baselineEn));

        return parent::setBaselineEn($baselineEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaselineEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaselineEn', array());

        return parent::getBaselineEn();
    }

}
