<?php

namespace Proxies\__CG__\Chaire\AccueilBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Highlight extends \Chaire\AccueilBundle\Entity\Highlight implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'id', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'title', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'baseLine', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'link', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'activated', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'filephoto', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'photolink');
        }

        return array('__isInitialized__', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'id', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'title', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'baseLine', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'link', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'activated', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'filephoto', '' . "\0" . 'Chaire\\AccueilBundle\\Entity\\Highlight' . "\0" . 'photolink');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Highlight $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseLine($baseLine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseLine', array($baseLine));

        return parent::setBaseLine($baseLine);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseLine', array());

        return parent::getBaseLine();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', array($link));

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', array());

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivated($activated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivated', array($activated));

        return parent::setActivated($activated);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivated', array());

        return parent::getActivated();
    }

    /**
     * {@inheritDoc}
     */
    public function getFilephoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilephoto', array());

        return parent::getFilephoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilephoto(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilephoto', array($file));

        return parent::setFilephoto($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotolink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotolink', array());

        return parent::getPhotolink();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotolink($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotolink', array($photo));

        return parent::setPhotolink($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

}
